version: '3'
services:
  money:
    build: money
    ports:
      - 8080:8080
      - 8081:8081
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:1.3.3.16
    restart: on-failure
    depends_on:
      - kafka
      - zookeeper
    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
    environment:
      - ZK_HOSTS=zookeeper
      - APPLICATION_SECRET=letmein
    ports:
      - 9000:9000
  envoy:
    image: envoyproxy/envoy:latest
    ports:
      - 10101:10101
      - 9902:9902
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - .docker/prometheus:/data
      - ./config/prometheus:/etc/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:5.4.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - .docker/grafana:/var/lib/grafana
  elasticsearch:
    image: elasticsearch:5
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:5
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./config/logstash:/etc/logstash/conf.d
    ports:
      - 9999:9999
    links:
      - elasticsearch
  kibana:
    image: kibana:5
    volumes:
      - ./config/kibana:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch